### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by fuleying** [tylin/coco-caption#22]
when I run ``cocoEvalCapDemo.ipynb``, it throws an exception:
```
setting up scorers...
Traceback (most recent call last):
  File "cocoEvalDemo.py", line 31, in <module>
    cocoEval.evaluate()
  File "/home/fuleying/coco-caption/pycocoevalcap/eval.py", line 31, in evaluate
    gts  = tokenizer.tokenize(gts)
  File "/home/fuleying/coco-caption/pycocoevalcap/tokenizer/ptbtokenizer.py", line 52, in tokenize
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by fuleying** [comment]
I have not installed java jre. Now have been solved.

**Comment by junha1125** [comment]
> java jre

Thanks! 
```bash
sudo apt update
sudo apt install default-jre
```
