### ISSUE TITLE
ValueError: invalid literal for float()

### ISSUE THREAD

**Issue by wjb123** [tylin/coco-caption#25]
when I use the coco-caption evaluation code, the bleu1-4 scores are normal, but the script always reports some errors on the meteor .  how can I deal with it?
    valid_score = scorer.score(gts_valid, samples_valid, dataset.valid_ids)
  File /cocoeval.py", line 72, in score
    print 'computing %s score...'%(scorer.method())
  File "/pycocoevalcap/meteor/meteor.py", line 42, in compute_score
    #print('{}\n'.format(eval_line))
ValueError: invalid literal for float(): 28.0 16.0 0.0 0.0 9.0 9.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 7.0 9.0 9.0

**Comment by ArnaudVella** [comment]
Did you solve this problem?

**Comment by wjb123** [comment]
Sorry, I also have no idea about it.

**Comment by sanyam5** [comment]
facing the same problem. was any of you able to fix it?

**Comment by muneebable** [comment]
````
ratio: 1.0076053968122858
Bleu_1: 0.644
Bleu_2: 0.456
Bleu_3: 0.309
Bleu_4: 0.209
computing METEOR score...
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    score = val_dataset.eval(result, checkpoint_path)
  File "/data1/home/mrim/hassanm/gve/pytorch-vision-language/utils/data/coco_dataset.py", line 211, in eval
    cocoEval.evaluate()
  File "/data1/home/mrim/hassanm/gve/pytorch-vision-language/pycocoevalcap/eval.py", line 50, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "/data1/home/mrim/hassanm/gve/pytorch-vision-language/pycocoevalcap/meteor/meteor.py", line 43, in compute_score
    scores.append(float(self.meteor_p.stdout.readline().strip()))
ValueError: could not convert string to float:
````

I am having the same problem. Can you please guide me?

**Comment by sanyam5** [comment]
@muneeb699 look at my pull request
